- name: install apache2
  apt: name=apache2 state=present

- name: update apache2 config
  copy: src=apache2.conf dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache2

- name: update apache2 envvars
  copy: src=apache2_envvars dest=/etc/apache2/envvars
  notify: restart apache2

- name: install git early
  apt: name={{ item }}
  with_items:
    - curl
    - man
    - git
    - ipmitool

- name: install bash-completion and paramiko (for helpers)
  apt: name={{ item }}
  with_items:
    - bash-completion
    - python-paramiko
    - python-dev
    - python-pip
    - python-netaddr

- name: install paramiko version 1.16
  command: pip install paramiko==1.16

- name: run apt-get update
  apt: update_cache=yes

- name: put rename script in /var/www
  copy: src=rename_eth_swp dest=/var/www/rename_eth_swp
