---
  - hosts: all
    become: yes
    roles:
      - { role: users, tags: 'users' }
      - { role: network, tags: 'network' }
      - { role: services, tags: 'services' }
      - { role: altdemo, tags: 'altdemo' }
